### ISSUE TITLE
CLANG 14 error while building 

### ISSUE THREAD

**Issue by rolavick** [STARlightsim/STARlight#6]
When trying to build STARlight of github version 8c2ae55df3c806e06e6d1b2473f62a78c6f15cde I got the following error

```
[ 84%] Building CXX object CMakeFiles/Starlib.dir/src/inputParser.cpp.o
/Users/repick/alice/upc/STARlight/STARlight/src/inputParser.cpp:239:9: error: variable 'nNonCriticalMissing' set but not used [-Werror,-Wunused-but-set-variable]
    int nNonCriticalMissing = 0;
        ^
1 error generated.
make[2]: *** [CMakeFiles/Starlib.dir/build.make:454: CMakeFiles/Starlib.dir/src/inputParser.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/Starlib.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

System: Macos Ventura 13.5.2
Cmake version: 3.27.6
Make version: 4.4.1
Clang version: 14.0.3

After some search I found out this is related to CLANG 14, which uses "-Wunused-but-set-variable" by default. I have temporarly fixed it by adding " -Wno-unused-but-set-variable " after "CXX_FLAGS = " in cmaked folder "CMakeFiles/Starlib.dir/flags.make"

Two notes:
1) My solution is rather a temporarly workaround. Maybe someone can find more elegant solution?
2) The compiler is right, the variable nNonCriticalMissing in inputParser.cpp is filled, but in the end the value is never used.

**Comment by SpencerKlein** [comment]
This should be fixed now.
